/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './modules/**/*.{js,ts,jsx,tsx}',
  ],
  corePlugins: {
    opacity: true,
  },
  variants: {
    // height: ['responsive', 'hover', 'focus', 'active', 'group-hover'],
    opacity: ['responsive', 'hover', 'focus', 'active', 'group-hover'],
  },
  //   extend: {
  //     //   height: {
  //     //     '480': '480px',
  //     //   },
  //     opacity: ['responsive', 'hover', 'focus', 'active', 'group-hover'],
  //   },
  theme: {
    opacity: {
      0: '0',
      25: '.25',
      50: '.5',
      75: '.75',
      10: '.1',
      20: '.2',
      30: '.3',
      40: '.4',
      50: '.5',
      60: '.6',
      70: '.7',
      80: '.8',
      90: '.9',
      100: '1',
    },
    fontFamily: {
      body: [
        'Montserrat',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
      sans: [
        'Montserrat',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
    },
    colors: {
      primary: {
        100: 'rgb(var(--tw-color-primary-100) / <alpha-value>)',
        200: 'rgb(var(--tw-color-primary-200) / <alpha-value>)',
        300: 'rgb(var(--tw-color-primary-300) / <alpha-value>)',
      },
      secondary: {
        100: 'rgb(var(--tw-color-secondary-100) / <alpha-value>)',
        200: 'rgb(var(--tw-color-secondary-200) / <alpha-value>)',
        300: 'rgb(var(--tw-color-secondary-300) / <alpha-value>)',
      },
      tertiary: {
        100: 'rgb(var(--tw-color-tertiary-100) / <alpha-value>)',
        200: 'rgb(var(--tw-color-tertiary-200) / <alpha-value>)',
        300: 'rgb(var(--tw-color-tertiary-300) / <alpha-value>)',
      },
      white: '#fff',
      black: '#000',
      dark: '#222222',
      gray: '#f8f8f8',
      darkgray: '#767e87',
      lightgray: '#BABABA',
      promo: '#EE6013',
    },
    spacing: {
      px: '10px',
      0: '0',
      0.5: '0.125rem',
      1: '0.25rem',
      1.5: '0.375rem',
      2: '0.5rem',
      2.5: '0.625rem',
      3: '0.75rem',
      3.5: '0.875rem',
      4: '1rem',
      5: '1rem',
      6: '1.5rem',
      7: '1.75rem',
      8: '2rem',
      9: '2.25rem',
      10: '2.5rem',
      11: '2.75rem',
      12: '3rem',
      14: '3.5rem',
      16: '4rem',
      20: '5rem',
      24: '6rem',
      28: '7rem',
      32: '8rem',
      36: '9rem',
      40: '10rem',
      44: '11rem',
      48: '12rem',
      52: '13rem',
      56: '14rem',
      60: '15rem',
      64: '16rem',
      72: '18rem',
      80: '20rem',
      96: '24rem',
    },
    screens: {
      sm: '768px', // => @media (min-width: 768px)
      md: '1024px', // => @media (min-width: 1024px)
      lg: '12380px', // => @media (min-width: 1280px)
    },
    height: { 480: '480px', screen: '100vh' },
  },
  plugins: [],
};
