/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
    fontFamily: {
      body: [
        'Montserrat',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
      sans: [
        'Montserrat',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
    },
    colors: {
      primary: {
        50: 'rgb(var(--tw-color-primary-50) / <alpha-value>)',
        100: 'rgb(var(--tw-color-primary-100) / <alpha-value>)',
        200: 'rgb(var(--tw-color-primary-200) / <alpha-value>)',
        300: 'rgb(var(--tw-color-primary-300) / <alpha-value>)',
        400: 'rgb(var(--tw-color-primary-400) / <alpha-value>)',
        500: 'rgb(var(--tw-color-primary-500) / <alpha-value>)',
        600: 'rgb(var(--tw-color-primary-600) / <alpha-value>)',
        700: 'rgb(var(--tw-color-primary-700) / <alpha-value>)',
        800: 'rgb(var(--tw-color-primary-800) / <alpha-value>)',
        900: 'rgb(var(--tw-color-primary-900) / <alpha-value>)',
      },
      dark: '#222222',
      gray: '#f8f8f8',
      darkgray: '#767e87',
    },
    spacing: {
      px: '10px',
      0: '0',
      0.5: '0.125rem',
      1: '0.25rem',
      1.5: '0.375rem',
      2: '0.5rem',
      2.5: '0.625rem',
      3: '0.75rem',
      3.5: '0.875rem',
      4: '1rem',
      5: '1rem',
      6: '1.5rem',
      7: '1.75rem',
      8: '2rem',
      9: '2.25rem',
      10: '2.5rem',
      11: '2.75rem',
      12: '3rem',
      14: '3.5rem',
      16: '4rem',
      20: '5rem',
      24: '6rem',
      28: '7rem',
      32: '8rem',
      36: '9rem',
      40: '10rem',
      44: '11rem',
      48: '12rem',
      52: '13rem',
      56: '14rem',
      60: '15rem',
      64: '16rem',
      72: '18rem',
      80: '20rem',
      96: '24rem',
    },
  },
  plugins: [],
};
